# Generated by Django 6.0.3 on 2026-03-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('training', 'Training'), ('matchday', 'Match Day'), ('academy', 'Academy'), ('team', 'Team Photo')], max_length=20)),
                ('caption', models.TextField(blank=True)),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_taken'],
            },
        ),
    ]
