# Generated by Django 6.0.3 on 2026-04-21 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_photo_options_photo_height_photo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['category', 'is_published'], name='gallery_pho_categor_28d3b4_idx'),
        ),
    ]
