# Generated by Django 6.0.3 on 2026-03-28 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_name', models.CharField(max_length=100)),
                ('away_team_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('is_home_game', models.BooleanField(default=True)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.competition')),
                ('our_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.team')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
