# Generated by Django 6.0.3 on 2026-04-21 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
        ('players', '0006_player_players_pla_team_id_1a80c1_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='our_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.team'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['is_completed', 'date'], name='fixtures_fi_is_comp_2c753b_idx'),
        ),
    ]
