# Generated by Django 6.0.3 on 2026-04-21 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_alter_fixture_our_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fixtures.competition'),
        ),
    ]
