# Generated by Django 6.0.3 on 2026-03-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founded_year', models.CharField(default='2024', max_length=10)),
                ('home_ground', models.CharField(default='TOC Turf', max_length=200)),
                ('district', models.CharField(default='Gorkha', max_length=100)),
                ('province', models.CharField(default='Gandaki Pradesh', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('our_story_heading', models.CharField(default='Born from the Hills', max_length=200)),
                ('our_story_body', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('values', models.TextField()),
                ('programmes_heading', models.CharField(default='Where We Are Today', max_length=200)),
                ('programmes_body', models.TextField()),
                ('active_programmes', models.TextField(help_text='One per line')),
                ('coming_soon_programmes', models.TextField(help_text='One per line')),
                ('ground_story', models.TextField()),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/HillyFielders/')),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Club Profile',
                'verbose_name_plural': 'Club Profile',
            },
        ),
    ]
