# Generated by Django 6.0.3 on 2026-03-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('mens-senior', "Men's Senior Team"), ('mens-u16', "Men's U-16"), ('mens-u14', "Men's U-14"), ('mens-u12', "Men's U-12"), ('womens-senior', "Women's Senior Team"), ('womens-u16', "Women's U-16"), ('womens-u14', "Women's U-14"), ('womens-u12', "Women's U-12")], max_length=20),
        ),
    ]
