# Generated by Django 6.0.3 on 2026-04-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_unique_jersey_per_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['programme__gender', 'order', 'name']},
        ),
        migrations.AlterField(
            model_name='team',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number appears first in navigation.'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from programme + name. You can override it.', max_length=60, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('programme', 'name')},
        ),
    ]
