# Generated by Django 6.0.3 on 2026-04-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_team_options_alter_team_order_alter_team_slug_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['team', 'is_active'], name='players_pla_team_id_1a80c1_idx'),
        ),
    ]
