# Generated by Django 6.0.3 on 2026-04-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_player_players_pla_team_id_1a80c1_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
